	nolist
;*----------------------------------------------*
;* ASCII constants								*
;*----------------------------------------------*
CTRLC		equ	0x03		;ASCII control-C
CR			equ	0x0d		;ASCII	Carriage Return
LF			equ	0x0a		;ASCII Line Feed
BS			equ	0x08		;ASCII backspace
XON			equ	0x11		;ASCII XON (CTRL-Q)
XOFF		equ	0x13		;ASCII XOFF (CTRL-S)
ESC			equ	0x1B		;ASCII Escape
DEL			equ	0x7f		;ASCII Delete
	list
